
services: 

  frontend:
      image: node:20.13
      environment:
        CHOKIDAR_USEPOLLING: "true"
      container_name: frontend
      volumes:
        - .:/app:cached
      working_dir: /app
      ports:
        - 3000:3000
      expose:
        - 3000
      command: npm start
